import 'dart:async';

import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';

import '../constants/app_colors.dart';
import '../constants/category_config.dart';
import '../models/reminder_model.dart';
import '../services/database_service.dart';
import '../services/alarm_service.dart';

class AddEditReminderScreen extends StatefulWidget {
  final ReminderCategory category;
  final ReminderModel? existingReminder;

  const AddEditReminderScreen({
    super.key,
    required this.category,
    this.existingReminder,
  });

  @override
  State<AddEditReminderScreen> createState() => _AddEditReminderScreenState();
}

class _AddEditReminderScreenState extends State<AddEditReminderScreen> {
  final _formKey = GlobalKey<FormState>();
  final _uuid = const Uuid();

  late Map<String, String> _categoryFields;
  late TimeOfDay _selectedTime;
  late ReminderRepeatMode _repeatMode;
  late List<int> _selectedDays;
  late String _confirmQuestion;
  bool _questionOverridden = false;
  bool _saving = false;

  // Day-of-week labels
  static const _dayLabels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];

  @override
  void initState() {
    super.initState();
    _initializeFields();
  }

  void _initializeFields() {
    final existing = widget.existingReminder;

    _categoryFields = Map<String, String>.from(existing?.categoryFields ?? {});
    _selectedTime = existing?.time ?? const TimeOfDay(hour: 8, minute: 0);
    _repeatMode = existing?.repeat ?? ReminderRepeatMode.once;
    _selectedDays = List<int>.from(existing?.days ?? []);
    _confirmQuestion = existing?.confirmQuestion ?? '';
    _questionOverridden = existing != null && existing.confirmQuestion != _autoGeneratedQuestion();
  }

  String get _categoryKey {
    switch (widget.category) {
      case ReminderCategory.medication:
        return 'medication';
      case ReminderCategory.meal:
        return 'meal';
      case ReminderCategory.hydration:
        return 'hydration';
      case ReminderCategory.exercise:
        return 'exercise';
      case ReminderCategory.sleep:
        return 'sleep';
      case ReminderCategory.selfCare:
        return 'selfCare';
      case ReminderCategory.custom:
        return 'custom';
    }
  }

  String _autoGeneratedQuestion() {
    return buildQuestion(widget.category, _categoryFields);
  }

  String _autoGeneratedTitle() {
    return buildTitle(widget.category, _categoryFields);
  }

  Future<void> _pickTime() async {
    final picked = await showTimePicker(
      context: context,
      initialTime: _selectedTime,
    );
    if (picked != null) {
      setState(() => _selectedTime = picked);
    }
  }

  void _toggleDay(int day) {
    setState(() {
      if (_selectedDays.contains(day)) {
        _selectedDays.remove(day);
      } else {
        _selectedDays.add(day);
      }
    });
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _saving = true);

    try {
      final title = _autoGeneratedTitle();
      final question = _questionOverridden || widget.category == ReminderCategory.custom
          ? _confirmQuestion
          : _autoGeneratedQuestion();

      final reminder = ReminderModel(
        id: widget.existingReminder?.id ?? _uuid.v4(),
        category: widget.category,
        title: title,
        categoryFields: Map.from(_categoryFields),
        confirmQuestion: question,
        time: _selectedTime,
        repeat: _repeatMode,
        days: List.from(_selectedDays),
        isEnabled: widget.existingReminder?.isEnabled ?? true,
        createdAt: widget.existingReminder?.createdAt ?? DateTime.now(),
      );

      if (widget.existingReminder != null) {
        await DatabaseService.updateReminder(reminder);
        AlarmService.cancel(reminder.id);
      } else {
        await DatabaseService.insertReminder(reminder);
      }

      if (reminder.isEnabled) {
        await AlarmService.schedule(reminder);
      }

      if (mounted) {
        Navigator.pop(context, true);
      }
    } catch (e) {
      debugPrint('Error saving reminder: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error saving reminder: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.existingReminder != null ? 'Edit Reminder' : 'New Reminder'),
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            // Category header
            _buildCategoryHeader(),
            const SizedBox(height: 24),

            // Category-specific fields
            _buildCategoryFields(),
            const SizedBox(height: 24),

            // Time picker
            _buildTimeSection(),
            const SizedBox(height: 24),

            // Repeat section
            _buildRepeatSection(),
            const SizedBox(height: 24),

            // Question preview / override
            _buildQuestionSection(),
            const SizedBox(height: 32),

            // Save button
            _buildSaveButton(),
            const SizedBox(height: 16),
          ],
        ),
      ),
    );
  }

  Widget _buildCategoryHeader() {
    final config = CategoryConfig.all[_categoryKey]!;
    return Row(
      children: [
        Text(config.icon, style: const TextStyle(fontSize: 32)),
        const SizedBox(width: 12),
        Text(
          config.label,
          style: Theme.of(context).textTheme.headlineMedium,
        ),
      ],
    );
  }

  Widget _buildCategoryFields() {
    final config = CategoryConfig.all[_categoryKey]!;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Details', style: Theme.of(context).textTheme.titleLarge),
        const SizedBox(height: 12),
        for (final fieldDef in config.fields)
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: fieldDef.type == FieldType.text
                ? TextFormField(
                    initialValue: _categoryFields[fieldDef.key] ?? '',
                    decoration: InputDecoration(
                      labelText: fieldDef.label,
                      hintText: fieldDef.label,
                      border: const OutlineInputBorder(),
                      filled: true,
                      fillColor: AppColors.surface,
                    ),
                    style: const TextStyle(color: AppColors.white),
                    validator: fieldDef.required
                        ? (v) => (v == null || v.trim().isEmpty) ? 'Required' : null
                        : null,
                    onChanged: (v) {
                      setState(() {
                        _categoryFields[fieldDef.key] = v;
                        if (!_questionOverridden && widget.category != ReminderCategory.custom) {
                          _confirmQuestion = _autoGeneratedQuestion();
                        }
                      });
                    },
                  )
                : DropdownButtonFormField<String>(
                    initialValue: _categoryFields[fieldDef.key]?.isNotEmpty == true
                        ? _categoryFields[fieldDef.key]
                        : fieldDef.options?.first,
                    decoration: InputDecoration(
                      labelText: fieldDef.label,
                      border: const OutlineInputBorder(),
                      filled: true,
                      fillColor: AppColors.surface,
                    ),
                    dropdownColor: AppColors.surface,
                    items: (fieldDef.options ?? [])
                        .map((o) => DropdownMenuItem(value: o, child: Text(o)))
                        .toList(),
                    onChanged: (v) {
                      setState(() {
                        _categoryFields[fieldDef.key] = v ?? '';
                        if (!_questionOverridden && widget.category != ReminderCategory.custom) {
                          _confirmQuestion = _autoGeneratedQuestion();
                        }
                      });
                    },
                  ),
          ),
      ],
    );
  }

  Widget _buildTimeSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Time', style: Theme.of(context).textTheme.titleLarge),
        const SizedBox(height: 8),
        InkWell(
          onTap: _pickTime,
          borderRadius: BorderRadius.circular(12),
          child: Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
            decoration: BoxDecoration(
              color: AppColors.surface,
              borderRadius: BorderRadius.circular(12),
            ),
            child: Row(
              children: [
                const Icon(Icons.access_time, color: AppColors.alarmAccent),
                const SizedBox(width: 12),
                Text(
                  _selectedTime.format(context),
                  style: Theme.of(context).textTheme.headlineMedium,
                ),
                const Spacer(),
                const Icon(Icons.edit, color: AppColors.textSecondary),
              ],
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildRepeatSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('Repeat', style: Theme.of(context).textTheme.titleLarge),
        const SizedBox(height: 8),
        Wrap(
          spacing: 8,
          children: [
            _repeatChip('Once', ReminderRepeatMode.once),
            _repeatChip('Daily', ReminderRepeatMode.daily),
            _repeatChip('Specific Days', ReminderRepeatMode.specificDays),
          ],
        ),
        if (_repeatMode == ReminderRepeatMode.specificDays) ...[
          const SizedBox(height: 12),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: List.generate(7, (i) {
              final day = i + 1; // 1=Mon..7=Sun
              final selected = _selectedDays.contains(day);
              return FilterChip(
                label: Text(_dayLabels[i]),
                selected: selected,
                onSelected: (_) => _toggleDay(day),
                selectedColor: AppColors.alarmAccent,
                checkmarkColor: AppColors.white,
                backgroundColor: AppColors.surface,
                labelStyle: TextStyle(
                  color: selected ? AppColors.white : AppColors.textSecondary,
                ),
              );
            }),
          ),
        ],
      ],
    );
  }

  Widget _repeatChip(String label, ReminderRepeatMode mode) {
    final selected = _repeatMode == mode;
    return ChoiceChip(
      label: Text(label),
      selected: selected,
      onSelected: (_) => setState(() => _repeatMode = mode),
      selectedColor: AppColors.alarmAccent,
      backgroundColor: AppColors.surface,
      labelStyle: TextStyle(
        color: selected ? AppColors.white : AppColors.textSecondary,
      ),
    );
  }

  Widget _buildQuestionSection() {
    final currentQuestion = _questionOverridden || widget.category == ReminderCategory.custom
        ? _confirmQuestion
        : _autoGeneratedQuestion();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text('Confirmation Question', style: Theme.of(context).textTheme.titleLarge),
            const Spacer(),
            if (widget.category != ReminderCategory.custom)
              TextButton.icon(
                onPressed: () => setState(() => _questionOverridden = !_questionOverridden),
                icon: Icon(
                  _questionOverridden ? Icons.lock : Icons.edit,
                  size: 16,
                ),
                label: Text(_questionOverridden ? 'Auto' : 'Edit'),
              ),
          ],
        ),
        const SizedBox(height: 8),
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: AppColors.surface,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: AppColors.alarmAccent.withValues(alpha: 0.3)),
          ),
          child: _questionOverridden || widget.category == ReminderCategory.custom
              ? TextFormField(
                  initialValue: _confirmQuestion,
                  decoration: const InputDecoration(
                    border: InputBorder.none,
                    hintText: 'Type your confirmation question...',
                  ),
                  style: const TextStyle(color: AppColors.white, fontSize: 16),
                  maxLines: 2,
                  validator: (v) => (v == null || v.trim().isEmpty) ? 'Question is required' : null,
                  onChanged: (v) => _confirmQuestion = v,
                )
              : Text(
                  currentQuestion,
                  style: const TextStyle(
                    color: AppColors.white,
                    fontSize: 16,
                    fontStyle: FontStyle.italic,
                  ),
                ),
        ),
      ],
    );
  }

  Widget _buildSaveButton() {
    return ElevatedButton(
      onPressed: _saving ? null : _save,
      style: ElevatedButton.styleFrom(
        backgroundColor: AppColors.successGreen,
        disabledBackgroundColor: AppColors.textSecondary,
      ),
      child: _saving
          ? const SizedBox(
              height: 20,
              width: 20,
              child: CircularProgressIndicator(strokeWidth: 2, color: AppColors.white),
            )
          : const Text('Save Reminder'),
    );
  }
}
